- name: Make a file
  hosts: all

  tasks:
    - name: Create a file
      copy:
        content: test
        dest: /tmp/test.txt
    - name: Test write to file
      lineinfile:
        line: "Test writing"
        path: /tmp/test.txt
    - name: Change perms
      file:
        path: /tmp/test.txt
        owner: "{{ansible_user_uid}}"
        group: "{{ansible_user_gid}}"
        mode: '0775'
    - name: cleanup
      file:
        path: /tmp/test.txt
        state: absent
      
